#SPDX-License-Identifier: MIT-0
---
# handlers file for ntp_role
- name: Create a subnet
  amazon.aws.ec2_vpc_subnet:
    state: present
    vpc_id: "{{vpc.vpc.id}}"
    cidr: "{{subnet_cidr}}"
    az: "{{region}}a"
    tags:
      Name: "{{project_name}}-subnet"
  register: subnet
  notify: 
    - Create an Internet gateway

- name: Create an Internet gateway
  amazon.aws.ec2_vpc_igw:
    vpc_id: "{{vpc.vpc.id}}"
    state: present
  register: igw
  notify:
    - Set up a route table

- name: Set up a route table
  amazon.aws.ec2_vpc_route_table:
    vpc_id: "{{vpc.vpc.id}}"
    region: "{{region}}"
    tags:
      Name: "{{project_name}}-rt"
    subnets:
      - "{{subnet.subnet.id}}"
    routes:
      - dest: "{{destination_cidr}}"
        gateway_id: "{{igw.gateway_id}}"
  register: route_table
  notify: 
    - Create a security group

- name: Create a security group
  amazon.aws.ec2_security_group:
    name: "{{project_name}}-sg"
    description: "Security group for {{project_name}}"
    vpc_id: "{{vpc.vpc.id}}"
    rules:
      - proto: "{{destination_protocol}}"
        ports:
          - "{{destination_port}}"
        cidr_ip: "{{destination_ip}}"
        rule_desc: allow all on port {{destination_port}}
  register: security_group
  notify:
    - Create key pair

- name: Create key pair
  ec2_key:
    name: "{{key_name}}"
    region: "{{region}}"
    state: present
  register: keypair
  notify: 
    - Save private key to file

- name: Save private key to file
  copy:
    content: "{{keypair.key.private_key}}"
    dest: "./{{key_name}}.pem"
  notify:
    - Create an EC2 instance

- name: Create an EC2 instance
  amazon.aws.ec2_instance:
    name: "{{project_name}}-instance"
    key_name: "{{key_name}}"
    vpc_subnet_id: "{{subnet.subnet.id}}"
    instance_type: "{{instance_type}}"
    security_group: "{{security_group.group_id}}"
    network_interfaces:
      - assign_public_ip: true
    image_id: "{{ami}}"
    wait: true
    count: 1
    placement:
      availability_zone: "{{region}}a"
    tags:
      Name: "{{project_name}}-instance"
  register: ec2
  notify: 
    - Add an instance to the inventory

- name: Add an instance to the inventory
  add_host:
    name: "{{project_name}}-instance"
    groups: launched
    ansible_user: "{{ec2_user}}"
    ansible_ssh_private_key_file: "./{{key_name}}.pem"
    ansible_host: "{{ec2.instances[0].public_ip_address}}"
  when: ec2.instances is defined
  notify: 
    - Wait for SSH to become available

- name: Wait for SSH to become available
  wait_for:
    host: "{{ec2.instances[0].public_ip_address}}"
    port: "{{destination_port}}"
    delay: 10
    timeout: 300
  when: ec2.instances is defined
  notify: 
    - Wait for the instance

- name: Wait for the instance
  ansible.builtin.wait_for:
    timeout: 60
  notify: 
    - Install a NTP package

- name: Install a NTP package
  ansible.builtin.apt:
    name: ntp
    state: present
    update_cache: true
  become: true
  when: ec2.instances is defined
  delegate_to: "{{project_name}}-instance"