#SPDX-License-Identifier: MIT-0
---
# vars file for ntp_role

# VPC configuration
project_name: ntp-service
region: us-east-1
vpc_cidr: 10.10.0.0/16

# Subnet configuration
subnet_cidr: 10.10.1.0/24

# Internet gateway configuration
destination_cidr: 0.0.0.0/0

# Security group configuration
destination_port: 22
destination_ip: 0.0.0.0/0
destination_protocol: tcp

# Key pair configuration
key_name: ntp_key

# Instance configuration
instance_type: t3.micro
ami: ami-0b6d9d3d33ba97d99
ec2_user: ubuntu